engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - src/modules/**
  - src/actions/**
  - src/reducers/**
  - src/repositories/**
exclude_paths:
- src/**/*.test.js
- node_modules/**/*
- public/**/*
- test/**/*
- dist/**/*
- coverage/**/*
- __mocks__/**/*
